update common dependencies
kaltura/playkit-js-dual-screen pull request #140
Opened 2024-06-24 12:20 UTC by Tzipi-kaltura

update common dependencies

2024-06-24 12:21 UTC, semarche-kaltura approved these changes

2024-06-25 11:54 UTC, semarche-kaltura requested changes
we have to resolve issue with multiscreen button before PR can be merged

2024-06-26 13:45 UTC, Tzipi-kaltura commented
yes we have https://kaltura.atlassian.net/browse/FEC-14020, this is not part of my ticket since it's not related to my changes. it caused by old changes.

2024-07-17 10:50 UTC, semarche-kaltura approved these changes

2024-07-17 10:59 UTC, merged