fix(SUP-38407): [GaTech] [Multistream - V7 Player] Child entries not loading high quality flavor assets
kaltura/playkit-js-dual-screen pull request #155
Opened 2024-09-11 11:27 UTC by Tzipi-kaltura

Issue:
Quality is not changed in childe entries when it is changed in the parent entry.

**Fix:**
Add listener to videotrackchange and change the quality manually to all the other entries.

part of - 

solves [SUP-38407](https://kaltura.atlassian.net/browse/SUP-38407)

2024-09-11 13:48 UTC, semarche-kaltura requested changes

2024-09-11 13:48 UTC, semarche-kaltura commented on src/dualscreen.tsx
> +    this.eventManager.listen(this.player, EventType.VIDEO_TRACK_CHANGED, (event) => {
do we need remove listener on reset?

2024-09-11 13:48 UTC, semarche-kaltura commented on src/dualscreen.tsx
> +      if(dualScreenPlayer.id != 'mainPlayer' && dualScreenPlayer.id != 'imagePlayer'){
1. use prettier.
there should be space between `if` and `(`, same between `)` and `{`
2. use strict compare `!==` that requires less resources
3. use enums
`IMAGE_PLAYER_ID` for 'imagePlayer'
`MAIN_PLAYER_ID` for 'mainPlayer'

2024-09-11 17:45 UTC, semarche-kaltura approved these changes

2024-09-11 17:45 UTC, semarche-kaltura commented on src/dualscreen.tsx
> +      if (dualScreenPlayer.id !== MAIN_PLAYER_ID && dualScreenPlayer.id !== IMAGE_PLAYER_ID) {
I would do
```
![MAIN_PLAYER_ID, IMAGE_PLAYER_ID].includes(dualScreenPlayer.id)
```
but thats only syntax, your changes looks good!

2024-09-15 07:36 UTC, MosheMaorKaltura commented on src/dualscreen.tsx
> +          dualScreenPlayer.player.changeChildQuality(selectedVideoTrack);
rename to changeQuality

2024-09-15 08:41 UTC, Tzipi-kaltura commented on src/dualscreen.tsx
> +          dualScreenPlayer.player.changeChildQuality(selectedVideoTrack);
done

2024-09-15 08:53 UTC, MosheMaorKaltura approved these changes

2024-09-15 10:32 UTC, merged