fix(SUP-45297):[Nomura] - Intermittent playback error with dual screen videos
kaltura/playkit-js-dual-screen pull request #163
Opened 2024-12-11 14:14 UTC by inbalvasserman

issue:
sometimes second stream doesn't get load and there is an error on screen

solution:
wait 1 second before try to change quality for second stream

solve [SUP-45297](https://kaltura.atlassian.net/browse/SUP-45297)

2024-12-11 15:53 UTC, semarche-kaltura requested changes

2024-12-11 15:53 UTC, semarche-kaltura commented on src/dualscreen.tsx
> +          }, 1000);
setTimeout might cause inconsistent behaviour despite of network, cpu, memory, etc...
I would recommend find and use player event then trigger `dualScreenPlayer.player.changeQuality` once the event dispatched.

2024-12-15 08:28 UTC, SivanA-Kaltura requested changes

2024-12-15 08:28 UTC, SivanA-Kaltura commented on src/dualscreen.tsx
> +          dualScreenPlayer.player.changeQuality(selectedVideoTrack)
```suggestion
          dualScreenPlayer.player.changeQuality(selectedVideoTrack);
```

2024-12-16 12:11 UTC, SivanA-Kaltura approved these changes

2024-12-16 15:53 UTC, semarche-kaltura approved these changes

2024-12-17 07:49 UTC, merged